apiVersion: v1
appVersion: "1.0"
description: A Helm chart for manage-case-assignment App
name: aac-manage-case-assignment
home: https://github.com/hmcts/aac-manage-case-assignment
version: 0.0.1
maintainers:
  - name: HMCTS CDM team
