apiVersion: v2
appVersion: "1.0"
description: A Helm chart for manage-case-assignment App
name: aac-manage-case-assignment
home: https://github.com/hmcts/aac-manage-case-assignment
version: 0.2.11
maintainers:
  - name: HMCTS CDM team
dependencies:
  - name: java
    version: 4.0.13
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
